"""Build the additive V13 import from the preserved public-place snapshot."""
from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / 'database/fixtures/places/catalog-2026-09-09.json'
OUTPUT = ROOT / 'backend/src/main/resources/db/migration/V13__import_related_place_candidates.sql'
MAPPING = {
    '개인컵할인카페': ('KR-CNP-GREEN-2026-A02', 'reusable-cup'),
    '제로웨이스트상점': ('KR-CNP-GREEN-2026-A04', 'refill'),
    '리필판매기': ('KR-CNP-GREEN-2026-A04', 'refill'),
    '무인회수기': ('KR-CNP-GREEN-2026-A08', 'recyclable-return'),
    '재활용정거장': ('KR-CNP-GREEN-2026-A08', 'recyclable-return'),
}


def build():
    fixture = json.loads(FIXTURE.read_text())
    rows = fixture['places']
    assert len(rows) == len({p['place_id'] for p in rows}) == 1373
    for p in rows:
        action, service = MAPPING[p['place_type']]
        assert any(l['action_id'] == action and l['relation_type'] == 'candidate_action'
                   and l['link_status'] == 'unverified' for l in p['original_links'])
        assert p['name'].strip() and p['address'].strip()
        assert (p['latitude'] is None and p['longitude'] is None) or (
            -90 <= p['latitude'] <= 90 and -180 <= p['longitude'] <= 180)
        p['action_id'], p['service_key'] = action, service
        p['source_id'] = 'legacy-places-' + hashlib.sha256('|'.join(p['source_labels']).encode()).hexdigest()[:16]
    data = json.dumps(rows, ensure_ascii=False, separators=(',', ':'))
    assert '$place_import$' not in data
    original = (ROOT / 'backend/src/main/resources/db/migration/V1__verified_catalog_and_user_schema.sql').read_text()
    start = original.index('CREATE FUNCTION benefit_lookup(')
    end = original.index('$$;', start) + 3
    lookup = original[start:end].replace('CREATE FUNCTION benefit_lookup(', 'CREATE OR REPLACE FUNCTION app.benefit_lookup(')
    lookup = lookup.replace("'district',pl.district_name,", "'district',COALESCE(pl.metadata->>'sigungu',pl.district_name),")
    lookup = lookup.replace("'source',s.payload)", """'source',s.payload,
 'relation_type',ap.relation_type,'mapping_basis',ap.mapping_basis,
 'latitude',pl.metadata->'latitude','longitude',pl.metadata->'longitude',
 'place_type',pl.metadata->>'place_type','source_checked_at',pl.metadata->>'source_checked_at')""")
    # Existing callers still receive every condition/source; only place data is extended.
    return '''-- Generated by database/build_place_mapping.py. Historical candidate links, not verified rewards.
ALTER TABLE app.place ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE app.action_place ADD COLUMN relation_type text NOT NULL DEFAULT 'registered'
 CHECK (relation_type IN ('registered','candidate_action'));
ALTER TABLE app.action_place ADD COLUMN mapping_basis text;
CREATE TEMP TABLE imported_places ON COMMIT DROP AS
 SELECT value AS data FROM jsonb_array_elements($place_import$''' + data + '''$place_import$::jsonb);
INSERT INTO app.place(place_id,title,address,district_name,metadata)
 SELECT data->>'place_id',data->>'name',data->>'address',
 (SELECT district_name FROM app.district WHERE district_name=data->>'sigungu'),
 data - 'action_id' - 'service_key' - 'source_id' FROM imported_places;
INSERT INTO app.catalog_source(program_key,source_id,payload)
 SELECT DISTINCT 'scheme:KR-CNP-GREEN-2026',data->>'source_id',jsonb_build_object(
 'id',data->>'source_id','title',data->'source_labels'->>0,'url','',
 'origin','legacy_place_catalog','description','기존 장소 목록의 출처명. 상세 원문 링크 미확보; 개별 참여·혜택 미확인.')
 FROM imported_places;
INSERT INTO app.action_place(program_key,action_id,place_id,service_key,source_id,schedule,status,relation_type,mapping_basis)
 SELECT 'scheme:KR-CNP-GREEN-2026',data->>'action_id',data->>'place_id',data->>'service_key',
 data->>'source_id','null'::jsonb,'unknown','candidate_action',
 '기존 장소 목록의 ' || (data->>'place_type') || ' 분류와 행동 후보 연결. 해당 제도 참여·혜택 적용은 미확인.'
 FROM imported_places;
''' + lookup + '\n'


if __name__ == '__main__':
    sql = build()
    if '--check' in sys.argv:
        assert OUTPUT.read_text() == sql, 'Generated migration differs from fixture'
        print('V13 matches preserved fixture; 1373 supported candidate links')
    else:
        OUTPUT.write_text(sql)
        print('Generated', OUTPUT.name)
