// Reviewed wording from database/fixtures/catalog and action_links.json.
// Program-specific action identity is retained for conditions, places and completion.
const descriptions: Record<string, { title: string; summary: string }> = {
  "scheme:G002/G002-A01": {"title": "실천기록·퀴즈·게임 참여하기", "summary": "기후행동1.5℃에 가입하고 실천을 기록하거나 퀴즈·게임에 참여해 보세요."},
  "scheme:G002/G002-A02": {"title": "스쿨챌린지 참여 알아보기", "summary": "스쿨챌린지의 이번 회차 모집 대상과 참여 절차를 확인해 보세요."},
  "scheme:G031/G031-A01": {"title": "에너지바우처 신청 조건 확인하기", "summary": "가구의 소득·세대원 조건을 살펴보고 에너지바우처 신청 방법을 확인해 보세요."},
  "scheme:G031/G031-A02": {"title": "연탄전환 바우처 신청 조건 확인하기", "summary": "연탄보일러를 다른 연료의 보일러로 교체한 가구를 위한 전환 지원 조건을 확인해 보세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A01": {"title": "전자영수증 발급하기", "summary": "전자영수증 발급 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A02": {"title": "텀블러·다회용컵 이용하기", "summary": "텀블러·다회용컵 이용 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A03": {"title": "일회용컵 반환하기", "summary": "일회용컵 반환 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A04": {"title": "리필스테이션 이용하기", "summary": "리필스테이션 이용 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A05": {"title": "다회용기 이용하기", "summary": "다회용기 이용 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A06": {"title": "무공해차 대여하기", "summary": "무공해차 대여 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A07": {"title": "친환경제품 구매하기", "summary": "친환경제품 구매 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A08": {"title": "고품질 재활용품 배출하기", "summary": "고품질 재활용품 배출 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A09": {"title": "폐휴대폰 반납하기", "summary": "폐휴대폰 반납 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A10": {"title": "미래세대실천행동하기", "summary": "미래세대실천행동 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A11": {"title": "공유자전거 이용하기", "summary": "공유자전거 이용 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A12": {"title": "잔반제로 실천하기", "summary": "잔반제로 실천 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A13": {"title": "나무심기하기", "summary": "나무심기 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A14": {"title": "가정용 베란다 태양광 설치하기", "summary": "가정용 베란다 태양광 설치 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A15": {"title": "재생원료 사용제품 구매하기", "summary": "재생원료 사용제품 구매 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A16": {"title": "장바구니 이용하기", "summary": "장바구니 이용 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:KR-CNP-GREEN-2026/KR-CNP-GREEN-2026-A17": {"title": "개인용기 식품 포장하기", "summary": "개인용기 식품 포장 실천에 참여해 보세요. 탄소중립포인트 가입과 해당 항목의 참여기업·인증 방법을 먼저 확인해 주세요."},
  "scheme:SDG-ZEV-2026/SDG-ZEV-2026-A01": {"title": "전기차 구매 지원 확인하기", "summary": "성동구 전기차 구매 지원의 대상 모델·신청 서류·남은 예산을 확인해 보세요."},
  "scheme:SDG-ZEV-2026/SDG-ZEV-2026-A02": {"title": "수소차 구매 지원 확인하기", "summary": "성동구 수소차 구매 지원의 대상 모델·신청 서류·남은 예산을 확인해 보세요."},
  "scheme:SDG-ZEV-2026/SDG-ZEV-2026-A03": {"title": "전기이륜차 구매 지원 확인하기", "summary": "성동구 전기이륜차 구매 지원의 대상 모델·신청 서류·남은 예산을 확인해 보세요."},
  "scheme:SEOUL-EM-BLDG-2026/SEOUL-EM-BLDG-2026-A01": {"title": "건물 에너지 절감하기 · 5~10% 미만", "summary": "전기·수도·도시가스 사용을 줄여 보세요. 이 항목의 기준은 과거 평균 대비 5% 이상~10% 미만 절감입니다."},
  "scheme:SEOUL-EM-BLDG-2026/SEOUL-EM-BLDG-2026-A02": {"title": "건물 에너지 절감하기 · 10~15% 미만", "summary": "전기·수도·도시가스 사용을 줄여 보세요. 이 항목의 기준은 과거 평균 대비 10% 이상~15% 미만 절감입니다."},
  "scheme:SEOUL-EM-BLDG-2026/SEOUL-EM-BLDG-2026-A03": {"title": "건물 에너지 절감하기 · 15% 이상", "summary": "전기·수도·도시가스 사용을 줄여 보세요. 이 항목의 기준은 과거 평균 대비 15% 이상 절감입니다."},
  "scheme:SEOUL-EM-BLDG-2026/SEOUL-EM-BLDG-2026-A04": {"title": "건물 에너지 절감하기 · 절감 유지", "summary": "전기·수도·도시가스 사용을 줄여 보세요. 이 항목의 기준은 직전 2회 연속 절감 후 0% 초과~5% 미만 절감 유지입니다."},
  "scheme:SEOUL-EM-BLDG-2026/SEOUL-EM-BLDG-2026-A05": {"title": "건물 에너지 절감하기 · 소상공인", "summary": "전기·수도·도시가스 사용을 줄여 보세요. 이 항목의 기준은 서울 소재 개인사업자 등 소상공인 단체회원, 10% 이상 절감입니다."},
  "scheme:SEOUL-EM-CAR-2026/SEOUL-EM-CAR-2026-A01": {"title": "자동차 주행거리 줄이기 · 10% 미만", "summary": "자동차 이용을 줄이고 시작·종료 주행거리를 등록해 보세요. 이 항목의 기준은 주행거리 감축 10% 미만 또는 1,000km 미만입니다."},
  "scheme:SEOUL-EM-CAR-2026/SEOUL-EM-CAR-2026-A02": {"title": "자동차 주행거리 줄이기 · 10~20% 미만", "summary": "자동차 이용을 줄이고 시작·종료 주행거리를 등록해 보세요. 이 항목의 기준은 주행거리 감축 10% 이상~20% 미만 또는 1,000~2,000km 미만입니다."},
  "scheme:SEOUL-EM-CAR-2026/SEOUL-EM-CAR-2026-A03": {"title": "자동차 주행거리 줄이기 · 20~30% 미만", "summary": "자동차 이용을 줄이고 시작·종료 주행거리를 등록해 보세요. 이 항목의 기준은 주행거리 감축 20% 이상~30% 미만 또는 2,000~3,000km 미만입니다."},
  "scheme:SEOUL-EM-CAR-2026/SEOUL-EM-CAR-2026-A04": {"title": "자동차 주행거리 줄이기 · 30~40% 미만", "summary": "자동차 이용을 줄이고 시작·종료 주행거리를 등록해 보세요. 이 항목의 기준은 주행거리 감축 30% 이상~40% 미만 또는 3,000~4,000km 미만입니다."},
  "scheme:SEOUL-EM-CAR-2026/SEOUL-EM-CAR-2026-A05": {"title": "자동차 주행거리 줄이기 · 40% 이상", "summary": "자동차 이용을 줄이고 시작·종료 주행거리를 등록해 보세요. 이 항목의 기준은 주행거리 감축 40% 이상 또는 4,000km 이상입니다."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A01": {"title": "음식물 감량 참여 등록하기", "summary": "RFID 세대 참여 확정에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A02": {"title": "음식물쓰레기 10~20% 미만 줄이기", "summary": "전년 동기간 대비 10% 이상~20% 미만 감량에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A03": {"title": "음식물쓰레기 20~30% 미만 줄이기", "summary": "전년 동기간 대비 20% 이상~30% 미만 감량에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A04": {"title": "음식물쓰레기 30% 이상 줄이기", "summary": "전년 동기간 대비 30% 이상 감량에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A05": {"title": "친환경 운전 실천하기 · 85~95점 미만", "summary": "현대·기아 커넥티드카 연계, 평가 직전 3개월 500km 이상, 점수 85~95점 미만에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A06": {"title": "친환경 운전 실천하기 · 95점 이상", "summary": "현대·기아 커넥티드카 연계, 평가 직전 3개월 500km 이상, 점수 95점 이상에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A07": {"title": "환경 퀴즈 참여하기", "summary": "누리집 환경 관련 퀴즈 참여에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A08": {"title": "온라인 환경 이벤트 참여하기", "summary": "서울시 지정 온라인 이벤트의 조건 충족에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A09": {"title": "환경 실천 이벤트 참여·인증하기", "summary": "서울시 지정 행동실천형 이벤트 참여·인증에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
  "scheme:SEOUL-EM-GREEN-2026/SEOUL-EM-GREEN-2026-A10": {"title": "환경 현장 행사·교육 참여하기", "summary": "서울시 주관 또는 지정 현장 행사·교육 참여에 해당하는 참여 방법과 인증 절차를 확인해 보세요."},
};

export function actionDescription(programKey: string, actionId: string) {
  return descriptions[`${programKey}/${actionId}`];
}
